application: timely-list
runtime: go
api_version: go1
version: auto

handlers:
  - url: /
    static_files: client/index.html
    upload: client/index.html

  - url: /src/
    static_dir: client/src

  - url: /bower_components/
    static_dir: client/bower_components

  - url: /data/
    static_dir: client/data
